version: "3"

services:
  demo_app:
    build:
      context: ./demo-app
      dockerfile: Dockerfile
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - testing_network
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - testing_network

networks:
  testing_network:

volumes:
  mongo:
