version: "3"

services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - testing_network

networks:
  testing_network:

volumes:
  mongo:
