version: "3"

services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  demo_app:
    build:
      context: .
      dockerfile: load-testing/Dockerfile
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - testing_network
  taurus:
    image: blazemeter/taurus
    container_name: taurus
    command: /TaurusLoadTesting/taurus/sample_execution.yaml
    volumes:
      - .:/TaurusLoadTesting
    depends_on:
      - demo_app
      - mongo
    networks:
      - testing_network

networks:
  testing_network:
volumes:
  mongo: